Ingredient.create(name: "mango")
Ingredient.create(name: "pineapple")
Ingredient.create(name: "baobab")
Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "pixie dust")
Ingredient.create(name: "elbow grease")
Ingredient.create(name: "blood sweat and tears")

Cocktail.create(name: "The Fruity Ellyn")
Cocktail.create(name: "The Sassy Marina")
Cocktail.create(name: "The Raggaetony Valerie")
Cocktail.create(name: "The Samba Gus")
Cocktail.create(name: "The Daniel & Tonic")

