Ingredient.create(name: "mango")
Ingredient.create(name: "pineapple")
Ingredient.create(name: "baobab")
Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "pixie dust")
Ingredient.create(name: "elbow grease")
Ingredient.create(name: "blood sweat and tears")

Cocktail.create(name: "Fruity Ellyn")
Cocktail.create(name: "Sassy Marina")
Cocktail.create(name: "Raggaetony Valerie")
Cocktail.create(name: "Samba Gus")
Cocktail.create(name: "Daniel & Tonic")

